name: sign_language_2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_otp_text_field: ^1.5.1+1
  image_picker: ^1.0.4
  cloud_firestore: ^5.6.5
  url_launcher: ^6.3.1
  line_awesome_flutter: ^3.0.1
  flutter_3d_controller: ^2.1.0
  flutter_downloader: ^1.10.0
#  geolocator: ^13.0.3
  google_maps_flutter: ^2.2.1
  geocoding: ^3.0.0
  shared_preferences: ^2.0.15  # Downgraded to a stable version
  permission_handler: ^11.0.0
  video_player: ^2.7.0
  speech_to_text: ^7.0.0
  provider: ^6.1.2
  camera: ^0.11.1
  flutter_slidable: ^4.0.0
  flutter_tts: ^4.2.2
  vibration: ^3.1.3
  model_viewer_plus: ^1.7.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  http: ^1.3.0
  location: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/welcome/
    - assets/images/google/
    - assets/images/instagram.png
    - assets/images/facebook.png
    - assets/images/twitter.png
    - assets/images/profile.png
    - assets/model/3dmodelnew.glb
