// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCDWb5R1b4uVL0wPiipUHibuQJJD5ATLo',
    appId: '1:1050865698734:web:e542edec1a4745e50caa3f',
    messagingSenderId: '1050865698734',
    projectId: 'sign-language-2-47d60',
    authDomain: 'sign-language-2-47d60.firebaseapp.com',
    storageBucket: 'sign-language-2-47d60.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE_fuSl07xPZvEI3k-Th-dubqej_MILf0',
    appId: '1:1050865698734:android:83568841adec547c0caa3f',
    messagingSenderId: '1050865698734',
    projectId: 'sign-language-2-47d60',
    storageBucket: 'sign-language-2-47d60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3DKpSFdxlmZcDuzOEu552w_GUzGBhsuw',
    appId: '1:1050865698734:ios:5f5caf24b2cb271e0caa3f',
    messagingSenderId: '1050865698734',
    projectId: 'sign-language-2-47d60',
    storageBucket: 'sign-language-2-47d60.firebasestorage.app',
    iosBundleId: 'com.example.signLanguage2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3DKpSFdxlmZcDuzOEu552w_GUzGBhsuw',
    appId: '1:1050865698734:ios:5f5caf24b2cb271e0caa3f',
    messagingSenderId: '1050865698734',
    projectId: 'sign-language-2-47d60',
    storageBucket: 'sign-language-2-47d60.firebasestorage.app',
    iosBundleId: 'com.example.signLanguage2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCDWb5R1b4uVL0wPiipUHibuQJJD5ATLo',
    appId: '1:1050865698734:web:6a62f057500d1ce10caa3f',
    messagingSenderId: '1050865698734',
    projectId: 'sign-language-2-47d60',
    authDomain: 'sign-language-2-47d60.firebaseapp.com',
    storageBucket: 'sign-language-2-47d60.firebasestorage.app',
  );

}